image: node:latest

job_build:
  stage: build
  script:
    - npm install
    - npm run build
    - npm run test
    - npm run deploy -- -d pitermarx-boilerplate-staging.surge.sh
  artifacts:
    paths:
      - public/
      
pages:
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
    - public/